export const labelBoxItems = [
    { label: 'pig' },
    { label: 'goat' },
    { label: 'rabbit' },
    { label: 'rooster' },
    { label: 'donkey' },
    { label: 'turtle' },
    { label: 'hamster' },
    { label: 'sheep' },
    { label: 'cow' },
    { label: 'parrot' },
    { label: 'cat' },
    { label: 'bird' },
    { label: 'horse' },
    { label: 'fish' },
    { label: 'dog' },
    // second list
    // { label: 'butterfly' },
    // { label: 'deer' },
    // { label: 'squirrel' },
    // { label: 'turkey' },
    // { label: 'koala' },
    // { label: 'kangaroo' },
    // { label: 'duck' },
    // { label: 'penguin' },
    // { label: 'fox' },
    // { label: 'goose' },
    // { label: 'frog' },
    // { label: 'panda' },
    // { label: 'chicken' },
    // { label: 'bee' },
    // { label: 'wolf' },
    // // third list
    // { label: 'hippo' },
    // { label: 'lion' },
    // { label: 'shark' },
    // { label: 'tiger' },
    // { label: 'peacock' },
    // { label: 'lizard' },
    // { label: 'rhino' },
    // { label: 'snake' },
    // { label: 'dolphin' },
    // { label: 'monkey' },
    // { label: 'crocodile' },
    // { label: 'zebra' },
    // { label: 'hedgehog' },
    // { label: 'bear' },
]